apiVersion: v1
kind: Service
metadata:
  name: edge-service-eureka
  labels:
    app: edge-service-eureka
spec:
  type: ClusterIP
  selector:
    app: edge-service-eureka
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9080