apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: springnative-backend-function
spec:
  template:
    spec:
      containers:
        - name: springnative-backend-function
          image: craftsman/springnative-backend-function:latest
          ports:
            - containerPort: 9003
          resources:
            requests:
              cpu: '0.1'
              memory: '128Mi'
            limits:
              cpu: '2'
              memory: '512Mi'
