############## Info properties ###############
info:
  system: '@project.artifactId@'
  app:
    name: '@project.artifactId@'
    version: '@project.version@'
############## Spring properties ###############    
spring:
  application:
    name: '@project.artifactId@'
  lifecycle:
    timeout-per-shutdown-phase: 15s
############## Eureka properties ###############  
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
############## Server properties ###############
server:
  port: 8761
  shutdown: graceful
############## Log properties ###############
logging:
  level:
    '[@project.groupId@]': DEBUG