############## Info properties ###############
info:
  system: discovery-service
  app:
    name: discovery-service
    version: 1.0.0-SNAPSHOT
############## Spring properties ###############    
spring:
  application:
    name: discovery-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
############## Eureka properties ###############  
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
############## Server properties ###############
server:
  port: 8761
  shutdown: graceful
############## Log properties ###############
logging:
  level:
    '[com.craftsman.discoveryservice]': DEBUG