############## Info properties ###############
info:
  system: '@project.artifactId@'
  app:
    name: '@project.artifactId@'
    version: '@project.version@'
############## Cloud properties ###############    
spring:
  application:
    name: '@project.artifactId@'
  profiles:
    active: dev,pre,pro
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cadb-craftsman/config-service-properties.git
          timeout: 5
          clone-on-start: true
          force-pull: true
        default-label: main
############## Eureka client properties ###############
eureka:
  client:
   register-with-eureka: true  
   serviceUrl:
      defaultZone: http://localhost:8761/eureka/   
############## Management properties ###############
management:
  endpoints:
    web:
      exposure:
        include: env, health, heapdump, info, loggers, mappings
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      application: '@project.artifactId@'        
############## Server properties ###############
server:
  port: 8888
  tomcat:
    connection-timeout: 5s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
############## Log properties ###############
logging:
  level:
    '[@project.groupId@]': DEBUG               